<?php

return [
  'scrollTime' => ['default' => '6:00'],
  'defaultView' => ['default' => 'month'],
  'dayOfMonthFormat' => ['default' => 'ddd DD'],
  'timeFormat' => ['default' => 'h(:mm)t'],
  'hidePastEvents' => ['default' => '0'],
  'locale' => ['default' => CRM_Core_I18n::getLocale()],
  'height' => ['default' => '500'],

  'civicalendar_scrolltime' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_scrolltime',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '6:00:00',
    'description' => ts('Scroll pane is initially scrolled down to 6:00 AM'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
    ],
    'option_values' => [
      '12:00:00' => '12:00 am',
      '1:00:00' => '1:00 am',
      '2:00:00' => '2:00 am',
      '3:00:00' => '3:00 am',
      '4:00:00' => '4:00 am',
      '5:00:00' => '5:00 am',
      '6:00:00' => '6:00 am',
      '7:00:00' => '7:00 am',
      '8:00:00' => '8:00 am',
      '9:00:00' => '9:00 am',
      '10:00:00' => '10:00 am',
    ],
  ],

  'civicalendar_defaultview' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_defaultview',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => 'month',
    'description' => ts('Default tab for calendar (month, week, day, agenda)'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
    ],
    'option_values' => [
      'month' => ts('month'),
      'agendaWeek' => ts('week'),
      'agendaDay' => ts('day'),
      'listMonth' => ts('agenda'),
    ],
  ],

  'civicalendar_dayofmonthformat' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_dayofmonthformat',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => 'ddd DD',
    'description' => ts('Day of Month Format (eg. ddd DD)'),
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 20,
    ],
  ],

  'civicalendar_timeformat' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_timeformat',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => 'h(:mm)t',
    'description' => ts('Time Format'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
    ],
    'option_values' => [
      'h:mm' => ts('5:00'),
      'h(:mm)t' => ts('5p'),
      'H:mm' => ts('17:00'),
      'H(:mm)' => ts('17'),
    ],
  ],

  'civicalendar_locale' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_locale',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => CRM_Core_I18n::getLocale(),
    'description' => ts('Locale'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
    ],
    'option_values' => [
      'en' => 'en',
      'af' => 'af',
      'ar-dz' => 'ar-dz',
      'ar-kw' => 'ar-kw',
      'ar-ly' => 'ar-ly',
      'ar-ma' => 'ar-ma',
      'ar-sa' => 'ar-sa',
      'ar-tn' => 'ar-tn',
      'ar' => 'ar',
      'bg' => 'bg',
      'bs' => 'bs',
      'ca' => 'ca',
      'cs' => 'cs',
      'da' => 'da',
      'de-at' => 'de-at',
      'de-ch' => 'de-ch',
      'de' => 'de',
      'el' => 'el',
      'en-au' => 'en-au',
      'en-ca' => 'en-ca',
      'en-gb' => 'en-gb',
      'en-ie' => 'en-ie',
      'en-nz' => 'en-nz',
      'es-do' => 'es-do',
      'es-us' => 'es-us',
      'es' => 'es',
      'et' => 'et',
      'eu' => 'eu',
      'fa' => 'fa',
      'fi' => 'fi',
      'fr-ca' => 'fr-ca',
      'fr-ch' => 'fr-ch',
      'fr' => 'fr',
      'gl' => 'gl',
      'he' => 'he',
      'hi' => 'hi',
      'hr' => 'hr',
      'hu' => 'hu',
      'id' => 'id',
      'is' => 'is',
      'it' => 'it',
      'ja' => 'ja',
      'ka' => 'ka',
      'kk' => 'kk',
      'ko' => 'ko',
      'lb' => 'lb',
      'lt' => 'lt',
      'lv' => 'lv',
      'mk' => 'mk',
      'ms-my' => 'ms-my',
      'ms' => 'ms',
      'nb' => 'nb',
      'nl-be' => 'nl-be',
      'nl' => 'nl',
      'nn' => 'nn',
      'pl' => 'pl',
      'pt-br' => 'pt-br',
      'pt' => 'pt',
      'ro' => 'ro',
      'ru' => 'ru',
      'sk' => 'sk',
      'sl' => 'sl',
      'sq' => 'sq',
      'sr-cyrl' => 'sr-cyrl',
      'sr' => 'sr',
      'sv' => 'sv',
      'th' => 'th',
      'tr' => 'tr',
      'uk' => 'uk',
      'vi' => 'vi',
      'zh-cn' => 'zh-cn',
      'zh-tw' => 'zh-tw',
    ],
  ],

  'civicalendar_hidepastevents' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_hidepastevents',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '0',
    'description' => ts('Hide past events'),
    'html_type' => 'Checkbox',
  ],

  'civicalendar_height' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_height',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '500',
    'description' => ts('Height (eg. 500)'),
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 20,
    ],
  ],
];
