<?php

return [
  'civicalendar_activity_types' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_activity_types',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => [],
    'description' => ts('Shows certain activity types on the calendar'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
      'class' => 'crm-select2',
    ],
    'multiple' => true,
    'pseudoconstant' => ['optionGroupName' => 'activity_type'],
  ],

  'civicalendar_event_types' => [
    'group_name' => 'Civicalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_event_types',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => [],
    'description' => ts('Shows certain event types on the calendar'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
      'class' => 'crm-select2',
    ],
    'multiple' => true,
    'pseudoconstant' => ['optionGroupName' => 'event_type'],
  ],

  'civicalendar_case_types' => [
    'group_name' => 'Civicalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar__case_types',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => [],
    'description' => ts('Shows certain case types on the calendar'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
      'class' => 'crm-select2',
    ],
    'multiple' => true,
    'option_values' => CRM_Case_PseudoConstant::caseType('title'),
  ],

  'civicalendar_scroll_time' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_scroll_time',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '6:00:00',
    'description' => ts('Scroll pane is initially scrolled down to'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
      'class' => 'crm-select2',
    ],
    'option_values' => [
      '12:00:00' => '12:00 am',
      '1:00:00' => '1:00 am',
      '2:00:00' => '2:00 am',
      '3:00:00' => '3:00 am',
      '4:00:00' => '4:00 am',
      '5:00:00' => '5:00 am',
      '6:00:00' => '6:00 am',
      '7:00:00' => '7:00 am',
      '8:00:00' => '8:00 am',
      '9:00:00' => '9:00 am',
      '10:00:00' => '10:00 am',
    ],
  ],

  'civicalendar_default_view' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_default_view',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => 'month',
    'description' => ts('Default tab for calendar (month, week, day, agenda)'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
      'class' => 'crm-select2',
    ],
    'option_values' => [
      'month' => ts('month'),
      'agendaWeek' => ts('week'),
      'agendaDay' => ts('day'),
      'listMonth' => ts('agenda'),
    ],
  ],

  'civicalendar_time_format' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_time_format',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '(h:mm)t',
    'description' => ts('Time Format'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
      'class' => 'crm-select2',
    ],
    'option_values' => [
      '(h:mm)t' => ts('5:00p'),
      'H:mm' => ts('17:00'),
    ],
  ],

  'civicalendar_locale' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_locale',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => 'en',
    'description' => ts('Locale'),
    'html_type' => 'Select',
    'html_attributes' => [
      'size' => 20,
      'class' => 'crm-select2',
    ],
    'option_values' => [
      'en' => 'English (en)',
      'af' => 'Afrikaans (af)',
      'ar-dz' => 'Arabic (Algeria) (ar-dz)',
      'ar-kw' => 'Arabic (Kuwait) (ar-kw)',
      'ar-ly' => 'Arabic (Libya) (ar-ly)',
      'ar-ma' => 'Arabic (Morocco) (ar-ma)',
      'ar-sa' => 'Arabic (Saudi Arabia) (ar-sa)',
      'ar-tn' => 'Arabic (Tunisia) (ar-tn)',
      'ar' => 'Arabic (ar)',
      'bg' => 'Bulgarian (bg)',
      'bs' => 'Croatian (bs)',
      'ca' => 'Catalan (ca)',
      'cs' => 'Czech (cs)',
      'da' => 'Danish (da)',
      'de-at' => 'German (Austria) (de-at)',
      'de-ch' => 'German (Swiss) (de-ch)',
      'de' => 'German (de)',
      'el' => 'Greek (el)',
      'en-au' => 'English (Australia)',
      'en-ca' => 'English (Canada)',
      'en-gb' => 'English (United Kingdom)',
      'en-ie' => 'English (Ireland)',
      'en-nz' => 'English (New Zealand)',
      'es-do' => 'Spanish (Dominican Republic)',
      'es-us' => 'English (United States)',
      'es' => 'Spanish (es)',
      'et' => 'Estonian (et)',
      'eu' => 'Basque (eu)',
      'fa' => 'Persian (fa)',
      'fi' => 'Finnish (fi)',
      'fr-ca' => 'French (Canada) (fr-ca)',
      'fr-ch' => 'French (Switzerland) (fr-ch)',
      'fr' => 'French (France)',
      'gl' => 'Galician (gl)',
      'he' => 'Hebrev (he)',
      'hi' => 'Hindi() (hi)',
      'hr' => 'Croatia (hr)',
      'hu' => 'Hungarian (hu)',
      'id' => 'Indonesian (id)',
      'is' => 'Icelandic (is)',
      'it' => 'Italian (it)',
      'ja' => 'Japanese (ja)',
      'ka' => 'Georgian (ka)',
      'kk' => 'Kazakh (kk)',
      'ko' => 'Korean (ko)',
      'lb' => 'Luxembourgish (lb)',
      'lt' => 'Lithuanian (lt)',
      'lv' => 'Latvian (lv)',
      'mk' => 'Macedonian (mk)',
      'ms-my' => 'Malay (Malaysia) (ms-my)',
      'ms' => 'Malay (ms)',
      'nb' => 'Norwegian (nb)',
      'nl-be' => 'Dutch (Belgium) (nl-be)',
      'nl' => 'Dutch (nl)',
      'nn' => 'Norwegian Nynorsk (nn)',
      'pl' => 'Polish (pl)',
      'pt-br' => 'Portuguese (Brazil) (pt-br)',
      'pt' => 'Portuguese (Portugal) (pt)',
      'ro' => 'Romanian, Moldavian, Moldovan (ro)',
      'ru' => 'Russian (ru)',
      'sk' => 'Slovak (sk)',
      'sl' => 'Slovene (sl)',
      'sq' => 'Albanian (sq)',
      'sr-cyrl' => 'Serbia Cyrillic (sr-cyrl)',
      'sr' => 'Serbian (sr)',
      'sv' => 'Swedish (sv)',
      'th' => 'Thai (th)',
      'tr' => 'Turkish (tr)',
      'uk' => 'Ukrainian (uk)',
      'vi' => 'Vietnamese (vi)',
      'zh-cn' => 'Chinese (China) (zh-cn)',
      'zh-tw' => 'Chinese (Taiwan) (zh-tw)',
    ],
  ],
  'civicalendar_include_contact_names_in_title' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_include_contact_names__in_title',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '0',
    'description' => ts('Include contact names in title'),
    'html_type' => 'Checkbox',
  ],

  'civicalendar_hide_past_events' => [
    'group_name' => 'CiviCalendar Settings',
    'group' => 'civicalendar',
    'name' => 'civicalendar_hide_past_events',
    'type' => 'String',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '0',
    'description' => ts('Hide past events'),
    'html_type' => 'Checkbox',
  ],
];
